import json

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# SnakyNet Massive 13x13 Self-Play Training on Colab Pro\n",
                "This notebook trains the 13x13 AlphaGo-style ResNet for the Snakey game using Google Colab A100 GPUs.\n",
                "Make sure your runtime is set to GPU (Runtime -> Change runtime type -> A100 GPU)."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from google.colab import drive\n",
                "drive.mount('/content/drive')\n",
                "import os\n",
                "os.makedirs('/content/drive/MyDrive/SnakyNet_Checkpoints', exist_ok=True)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "!rm -rf /content/funSearch2-main\n",
                "!rm -rf /content/main.zip\n",
                "!wget -q https://github.com/aanderson3456/funSearch2/archive/refs/heads/main.zip\n",
                "!unzip -q main.zip\n",
                "import sys\n",
                "sys.path.append('/content/funSearch2-main/big_nn')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import torch\n",
                "import torch.nn.functional as F\n",
                "import torch.optim as optim\n",
                "import numpy as np\n",
                "import os, glob\n",
                "from env import SnakyEnv\n",
                "from resnet import SnakyNet\n",
                "from mcts import MCTS\n",
                "\n",
                "class ReplayBuffer:\n",
                "    def __init__(self, capacity=100000):\n",
                "        self.capacity = capacity\n",
                "        self.buffer = []\n",
                "        \n",
                "    def add(self, data):\n",
                "        self.buffer.extend(data)\n",
                "        if len(self.buffer) > self.capacity:\n",
                "            self.buffer = self.buffer[-self.capacity:]\n",
                "            \n",
                "    def sample(self, batch_size):\n",
                "        idx = np.random.choice(len(self.buffer), batch_size, replace=False)\n",
                "        return [self.buffer[i] for i in idx]\n",
                "\n",
                "def self_play(model, num_games=20, mcts_searches=50, device='cuda'):\n",
                "    mcts = MCTS(model, num_searches=mcts_searches, device=device)\n",
                "    all_data = []\n",
                "    \n",
                "    for g in range(num_games):\n",
                "        env = SnakyEnv(size=13)\n",
                "        game_data = []\n",
                "        \n",
                "        while not env.done:\n",
                "            action_probs = mcts.search(env, add_noise=True)\n",
                "            game_data.append((env.maker_board, env.breaker_board, env.current_player, action_probs))\n",
                "            \n",
                "            if len(game_data) < 15:\n",
                "                action = np.random.choice(len(action_probs), p=action_probs)\n",
                "            else:\n",
                "                action = np.argmax(action_probs)\n",
                "                \n",
                "            env.step(action)\n",
                "            \n",
                "        v = 1.0 if env.winner == 1 else -1.0\n",
                "        \n",
                "        augmented_data = []\n",
                "        for mb, bb, cp, policy in game_data:\n",
                "            symmetries = env.get_symmetries(mb, bb, policy)\n",
                "            for s_mb, s_bb, s_policy in symmetries:\n",
                "                augmented_data.append((s_mb, s_bb, cp, s_policy, v))\n",
                "                \n",
                "        all_data.extend(augmented_data)\n",
                "        print(f'Game {g+1}/{num_games} finished. Winner: {\"Maker\" if env.winner==1 else \"Breaker\"}. Moves: {len(game_data)}')\n",
                "        \n",
                "    return all_data\n",
                "\n",
                "def train(model, buffer, batch_size=256, epochs=5, lr=0.001, device='cuda'):\n",
                "    optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=1e-4)\n",
                "    model.train()\n",
                "    total_loss = 0\n",
                "    \n",
                "    for epoch in range(epochs):\n",
                "        data = buffer.sample(batch_size)\n",
                "        states = np.zeros((batch_size, 3, 13, 13), dtype=np.float32)\n",
                "        target_policies = np.zeros((batch_size, 169), dtype=np.float32)\n",
                "        target_values = np.zeros((batch_size, 1), dtype=np.float32)\n",
                "        \n",
                "        for i, (mb, bb, cp, p, v) in enumerate(data):\n",
                "            for bit in range(169):\n",
                "                y, x = divmod(bit, 13)\n",
                "                if mb & (1 << bit):\n",
                "                    states[i, 0, y, x] = 1.0\n",
                "                if bb & (1 << bit):\n",
                "                    states[i, 1, y, x] = 1.0\n",
                "            states[i, 2, :, :] = 1.0 if cp == 1 else 0.0\n",
                "            target_policies[i] = p\n",
                "            target_values[i] = v\n",
                "            \n",
                "        states = torch.tensor(states, dtype=torch.float32, device=device)\n",
                "        target_policies = torch.tensor(target_policies, dtype=torch.float32, device=device)\n",
                "        target_values = torch.tensor(target_values, dtype=torch.float32, device=device)\n",
                "        \n",
                "        optimizer.zero_grad()\n",
                "        out_policy, out_value = model(states)\n",
                "        \n",
                "        log_probs = F.log_softmax(out_policy, dim=1)\n",
                "        policy_loss = -(target_policies * log_probs).sum(dim=1).mean()\n",
                "        value_loss = F.mse_loss(out_value, target_values)\n",
                "        \n",
                "        loss = policy_loss + value_loss\n",
                "        loss.backward()\n",
                "        optimizer.step()\n",
                "        total_loss += loss.item()\n",
                "        \n",
                "    return total_loss / epochs"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Force CUDA\n",
                "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
                "print(f'Using device: {device}')\n",
                "if device.type == 'cuda':\n",
                "    print(f'GPU Name: {torch.cuda.get_device_name(0)}')\n",
                "\n",
                "model = SnakyNet(num_resBlocks=16, num_channels=256, board_size=13).to(device)\n",
                "buffer = ReplayBuffer(capacity=100000)\n",
                "\n",
                "import re\n",
                "drive_models = glob.glob(\"/content/drive/MyDrive/SnakyNet_Checkpoints/snaky_large_model_it*.pt\")\n",
                "root_models = glob.glob(\"/content/drive/MyDrive/snaky_large_model_it*.pt\")\n",
                "all_models = drive_models + root_models\n",
                "\n",
                "start_iteration = 13\n",
                "if all_models:\n",
                "    def get_it(path):\n",
                "        m = re.search(r'it(\\d+)\\.pt', path)\n",
                "        return int(m.group(1)) if m else -1\n",
                "    latest_model_path = max(all_models, key=get_it)\n",
                "    start_iteration = get_it(latest_model_path) + 1\n",
                "    print(f\"\\nFound checkpoint: {latest_model_path}\")\n",
                "    loaded = torch.load(latest_model_path, weights_only=False, map_location=device)\n",
                "    if isinstance(loaded, dict):\n",
                "        model.load_state_dict(loaded)\n",
                "        print(\"Successfully loaded weights from state_dict!\")\n",
                "    else:\n",
                "        model.load_state_dict(loaded.state_dict())\n",
                "        print(\"Successfully extracted and loaded weights from full model!\")\n",
                "else:\n",
                "    print(\"\\nNo checkpoints found. Starting from scratch!\")\n",
                "\n",
                "iterations = 1000\n",
                "games_per_iter = 100  # A100 is blazing fast\n",
                "batch_size = 512      # A100 has huge VRAM\n",
                "\n",
                "for it in range(start_iteration, iterations):\n",
                "    print(f'\\n--- Iteration {it}/{iterations} ---')\n",
                "    model.eval()\n",
                "    print('Starting Self-Play...')\n",
                "    data = self_play(model, num_games=games_per_iter, mcts_searches=100, device=device)\n",
                "    buffer.add(data)\n",
                "    \n",
                "    if len(buffer.buffer) >= batch_size: \n",
                "        loss = train(model, buffer, batch_size=batch_size, epochs=10, device=device)\n",
                "        print(f'Training Loss: {loss:.4f}')\n",
                "        \n",
                "    # Always save properly as state_dict so it loads anywhere!\n",
                "    save_path = f'/content/drive/MyDrive/SnakyNet_Checkpoints/snaky_large_model_it{it}.pt'\n",
                "    torch.save(model.state_dict(), save_path)\n",
                "    print(f'Saved Checkpoint to Google Drive! ({save_path})')\n"
            ]
        }
    ],
    "metadata": {
        "accelerator": "GPU",
        "colab": {
            "gpuType": "A100",
            "provenance": []
        },
        "kernelspec": {
            "display_name": "Python 3",
            "name": "python3"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 0
}

with open("colab_training.ipynb", "w") as f:
    json.dump(notebook, f, indent=2)
print("Training notebook generated!")
