import json

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# SnakyNet Massive 13x13 Self-Play Training on Colab Pro (VERSION 5)\n",
                "This notebook trains the 13x13 AlphaGo-style ResNet for the Snakey game using Google Colab A100 GPUs.\n",
                "**Updates in V5:** Completely rewrote the environment encoder and MCTS traversal algorithms. 100% of Python bottlenecks have been removed. This pushes the Python interpreter to its absolute theoretical limits. Expect < 5 minutes per generation!"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from google.colab import drive\n",
                "drive.mount('/content/drive')\n",
                "import os\n",
                "os.makedirs('/content/drive/MyDrive/SnakyNet_Checkpoints', exist_ok=True)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "!rm -rf /content/funSearch2-main\n",
                "!rm -rf /content/main.zip\n",
                "!wget -q https://github.com/aanderson3456/funSearch2/archive/refs/heads/main.zip\n",
                "!unzip -q main.zip\n",
                "import sys\n",
                "sys.path.append('/content/funSearch2-main/big_nn')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import torch\n",
                "import torch.nn.functional as F\n",
                "import torch.optim as optim\n",
                "import numpy as np\n",
                "import os, glob, math\n",
                "from env import SnakyEnv\n",
                "from resnet import SnakyNet\n",
                "\n",
                "class ReplayBuffer:\n",
                "    def __init__(self, capacity=100000):\n",
                "        self.capacity = capacity\n",
                "        self.buffer = []\n",
                "        \n",
                "    def add(self, data):\n",
                "        self.buffer.extend(data)\n",
                "        if len(self.buffer) > self.capacity:\n",
                "            self.buffer = self.buffer[-self.capacity:]\n",
                "            \n",
                "    def sample(self, batch_size):\n",
                "        idx = np.random.choice(len(self.buffer), batch_size, replace=False)\n",
                "        return [self.buffer[i] for i in idx]\n",
                "\n",
                "class FastSnakyEnv:\n",
                "    def __init__(self, size=13):\n",
                "        self.size = size\n",
                "        self.maker_board = 0\n",
                "        self.breaker_board = 0\n",
                "        self.current_player = 1 \n",
                "        self.done = False\n",
                "        self.winner = 0\n",
                "        self.occupied_array = np.zeros(size * size, dtype=bool)\n",
                "        self.maker_array = np.zeros(size * size, dtype=np.float32)\n",
                "        self.breaker_array = np.zeros(size * size, dtype=np.float32)\n",
                "        \n",
                "        temp_env = SnakyEnv(size=size)\n",
                "        self.win_masks = temp_env.win_masks\n",
                "\n",
                "    def get_legal_moves(self):\n",
                "        return np.where(~self.occupied_array)[0].tolist()\n",
                "        \n",
                "    def step(self, move):\n",
                "        move = int(move)\n",
                "        if self.done:\n",
                "            return self.done, self.winner\n",
                "            \n",
                "        self.occupied_array[move] = True\n",
                "        \n",
                "        if self.current_player == 1:\n",
                "            self.maker_board |= (1 << move)\n",
                "            self.maker_array[move] = 1.0\n",
                "            mb = self.maker_board\n",
                "            for m in self.win_masks:\n",
                "                if (mb & m) == m:\n",
                "                    self.done = True\n",
                "                    self.winner = 1\n",
                "                    return self.done, self.winner\n",
                "        else:\n",
                "            self.breaker_board |= (1 << move)\n",
                "            self.breaker_array[move] = 1.0\n",
                "            \n",
                "        if (self.maker_board | self.breaker_board) == ((1 << (self.size * self.size)) - 1):\n",
                "            self.done = True\n",
                "            self.winner = 0\n",
                "            return self.done, self.winner\n",
                "            \n",
                "        self.current_player *= -1\n",
                "        return self.done, self.winner\n",
                "        \n",
                "    def get_symmetries(self, maker_board, breaker_board, policy):\n",
                "        temp_env = SnakyEnv(size=self.size)\n",
                "        return temp_env.get_symmetries(maker_board, breaker_board, policy)\n",
                "\n",
                "def clone_env(env):\n",
                "    new_env = object.__new__(FastSnakyEnv)\n",
                "    new_env.size = env.size\n",
                "    new_env.maker_board = env.maker_board\n",
                "    new_env.breaker_board = env.breaker_board\n",
                "    new_env.current_player = env.current_player\n",
                "    new_env.done = env.done\n",
                "    new_env.winner = env.winner\n",
                "    new_env.occupied_array = env.occupied_array.copy()\n",
                "    new_env.maker_array = env.maker_array.copy()\n",
                "    new_env.breaker_array = env.breaker_array.copy()\n",
                "    new_env.win_masks = env.win_masks\n",
                "    return new_env\n",
                "\n",
                "class FastNode:\n",
                "    def __init__(self, parent=None, action_idx_in_parent=None):\n",
                "        self.parent = parent\n",
                "        self.action_idx_in_parent = action_idx_in_parent\n",
                "        self.is_expanded_flag = False\n",
                "        self.total_visits = 0\n",
                "        \n",
                "    def is_expanded(self):\n",
                "        return self.is_expanded_flag\n",
                "        \n",
                "    def expand(self, legal_moves, priors):\n",
                "        self.is_expanded_flag = True\n",
                "        self.legal_moves = np.array(legal_moves, dtype=np.int32)\n",
                "        num_moves = len(legal_moves)\n",
                "        \n",
                "        self.visits = np.zeros(num_moves, dtype=np.float32)\n",
                "        self.values = np.zeros(num_moves, dtype=np.float32)\n",
                "        self.priors = priors[legal_moves]\n",
                "        \n",
                "        p_sum = np.sum(self.priors)\n",
                "        if p_sum > 0:\n",
                "            self.priors /= p_sum\n",
                "        else:\n",
                "            if num_moves > 0:\n",
                "                self.priors = np.ones(num_moves, dtype=np.float32) / num_moves\n",
                "                \n",
                "        self.children = [None] * num_moves\n",
                "\n",
                "def _encode_state_batch(envs, device):\n",
                "    n = len(envs)\n",
                "    size = envs[0].size\n",
                "    states = np.empty((n, 3, size * size), dtype=np.float32)\n",
                "    \n",
                "    states[:, 0] = [e.maker_array for e in envs]\n",
                "    states[:, 1] = [e.breaker_array for e in envs]\n",
                "    cp = np.array([e.current_player for e in envs], dtype=np.float32)\n",
                "    states[:, 2] = (cp == 1)[:, None]\n",
                "    \n",
                "    states = states.reshape(n, 3, size, size)\n",
                "    return torch.tensor(states, dtype=torch.float32, device=device)\n",
                "\n",
                "def batched_search(model, envs, num_searches, c_puct=1.0, add_noise=False, device='cuda'):\n",
                "    roots = [FastNode() for _ in range(len(envs))]\n",
                "    \n",
                "    states_tensor = _encode_state_batch(envs, device)\n",
                "    with torch.no_grad():\n",
                "        policy_logits, _ = model(states_tensor)\n",
                "        policies = F.softmax(policy_logits, dim=1).cpu().numpy()\n",
                "        \n",
                "    for i, env in enumerate(envs):\n",
                "        legal_moves = env.get_legal_moves()\n",
                "        roots[i].expand(legal_moves, policies[i])\n",
                "        if add_noise and len(legal_moves) > 0:\n",
                "            dirichlet_alpha = 0.3\n",
                "            dirichlet_noise = np.random.dirichlet([dirichlet_alpha] * len(legal_moves))\n",
                "            frac = 0.25\n",
                "            roots[i].priors = (1 - frac) * roots[i].priors + frac * dirichlet_noise\n",
                "\n",
                "    for _ in range(num_searches):\n",
                "        search_envs = [clone_env(env) for env in envs]\n",
                "        search_nodes = [root for root in roots]\n",
                "        \n",
                "        for i in range(len(envs)):\n",
                "            node = search_nodes[i]\n",
                "            env = search_envs[i]\n",
                "            \n",
                "            while node.is_expanded():\n",
                "                if len(node.legal_moves) == 0:\n",
                "                    break\n",
                "                    \n",
                "                q = np.divide(node.values, node.visits, out=np.zeros_like(node.values), where=node.visits!=0)\n",
                "                if env.current_player == -1:\n",
                "                    q = -q\n",
                "                u = c_puct * node.priors * math.sqrt(node.total_visits) / (1.0 + node.visits)\n",
                "                ucb = q + u\n",
                "                best_idx = np.argmax(ucb)\n",
                "                \n",
                "                if node.children[best_idx] is None:\n",
                "                    node.children[best_idx] = FastNode(parent=node, action_idx_in_parent=best_idx)\n",
                "                    \n",
                "                node = node.children[best_idx]\n",
                "                best_action = node.parent.legal_moves[best_idx]\n",
                "                env.step(best_action)\n",
                "                \n",
                "            search_nodes[i] = node\n",
                "            \n",
                "        states_to_eval = []\n",
                "        eval_indices = []\n",
                "        for i in range(len(envs)):\n",
                "            if not search_envs[i].done:\n",
                "                states_to_eval.append(search_envs[i])\n",
                "                eval_indices.append(i)\n",
                "            else:\n",
                "                v = 1.0 if search_envs[i].winner == 1 else -1.0\n",
                "                node = search_nodes[i]\n",
                "                while node.parent is not None:\n",
                "                    node.total_visits += 1\n",
                "                    p = node.parent\n",
                "                    idx = node.action_idx_in_parent\n",
                "                    p.visits[idx] += 1\n",
                "                    p.values[idx] += v\n",
                "                    node = p\n",
                "                node.total_visits += 1\n",
                "                \n",
                "        if states_to_eval:\n",
                "            states_tensor = _encode_state_batch(states_to_eval, device)\n",
                "            with torch.no_grad():\n",
                "                policy_logits, values = model(states_tensor)\n",
                "                policies = F.softmax(policy_logits, dim=1).cpu().numpy()\n",
                "                values = values.cpu().numpy()\n",
                "                \n",
                "            for idx, i in enumerate(eval_indices):\n",
                "                node = search_nodes[i]\n",
                "                env = search_envs[i]\n",
                "                policy = policies[idx]\n",
                "                v = values[idx][0]\n",
                "                \n",
                "                legal_moves = env.get_legal_moves()\n",
                "                node.expand(legal_moves, policy)\n",
                "                \n",
                "                while node.parent is not None:\n",
                "                    node.total_visits += 1\n",
                "                    p = node.parent\n",
                "                    idx_in_p = node.action_idx_in_parent\n",
                "                    p.visits[idx_in_p] += 1\n",
                "                    p.values[idx_in_p] += v\n",
                "                    node = p\n",
                "                node.total_visits += 1\n",
                "                \n",
                "    action_probs_batch = []\n",
                "    for i in range(len(envs)):\n",
                "        action_probs = np.zeros(envs[i].size * envs[i].size)\n",
                "        root = roots[i]\n",
                "        for idx_in_p, move in enumerate(root.legal_moves):\n",
                "            action_probs[move] = root.visits[idx_in_p] / num_searches\n",
                "        \n",
                "        s = np.sum(action_probs)\n",
                "        if s > 0:\n",
                "            action_probs = action_probs / s\n",
                "        action_probs_batch.append(action_probs)\n",
                "        \n",
                "    return action_probs_batch\n",
                "\n",
                "def self_play(model, num_games=100, mcts_searches=100, device='cuda'):\n",
                "    envs = [FastSnakyEnv(size=13) for _ in range(num_games)]\n",
                "    all_data = []\n",
                "    \n",
                "    active_indices = list(range(num_games))\n",
                "    game_data = [[] for _ in range(num_games)]\n",
                "    games_finished = 0\n",
                "    \n",
                "    move_count = 0\n",
                "    while active_indices:\n",
                "        move_count += 1\n",
                "        print(f\"\\rProcessing move {move_count} simultaneously for {len(active_indices)} active games...\", end='')\n",
                "        active_envs = [envs[i] for i in active_indices]\n",
                "        action_probs_batch = batched_search(model, active_envs, mcts_searches, add_noise=True, device=device)\n",
                "        \n",
                "        next_active = []\n",
                "        for idx, env_idx in enumerate(active_indices):\n",
                "            env = envs[env_idx]\n",
                "            action_probs = action_probs_batch[idx]\n",
                "            game_data[env_idx].append((env.maker_board, env.breaker_board, env.current_player, action_probs))\n",
                "            \n",
                "            if len(game_data[env_idx]) < 15:\n",
                "                action = np.random.choice(len(action_probs), p=action_probs)\n",
                "            else:\n",
                "                action = np.argmax(action_probs)\n",
                "                \n",
                "            env.step(action)\n",
                "            \n",
                "            if not env.done:\n",
                "                next_active.append(env_idx)\n",
                "            else:\n",
                "                v = 1.0 if env.winner == 1 else -1.0\n",
                "                augmented_data = []\n",
                "                for mb, bb, cp, policy in game_data[env_idx]:\n",
                "                    symmetries = env.get_symmetries(mb, bb, policy)\n",
                "                    for s_mb, s_bb, s_policy in symmetries:\n",
                "                        augmented_data.append((s_mb, s_bb, cp, s_policy, v))\n",
                "                all_data.extend(augmented_data)\n",
                "                games_finished += 1\n",
                "                \n",
                "        active_indices = next_active\n",
                "        \n",
                "    print(f\"\\nFinished all {num_games} games!\")\n",
                "    return all_data\n",
                "\n",
                "def train(model, buffer, batch_size=256, epochs=5, lr=0.001, device='cuda'):\n",
                "    optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=1e-4)\n",
                "    model.train()\n",
                "    total_loss = 0\n",
                "    \n",
                "    for epoch in range(epochs):\n",
                "        data = buffer.sample(batch_size)\n",
                "        states = np.zeros((batch_size, 3, 169), dtype=np.float32)\n",
                "        target_policies = np.zeros((batch_size, 169), dtype=np.float32)\n",
                "        target_values = np.zeros((batch_size, 1), dtype=np.float32)\n",
                "        \n",
                "        mb_arr = np.array([item[0] for item in data], dtype=object)\n",
                "        bb_arr = np.array([item[1] for item in data], dtype=object)\n",
                "        shifts = 1 << np.arange(169, dtype=object)\n",
                "        states[:, 0, :] = (mb_arr[:, None] & shifts) != 0\n",
                "        states[:, 1, :] = (bb_arr[:, None] & shifts) != 0\n",
                "        cp = np.array([item[2] for item in data])\n",
                "        states[:, 2, :] = (cp == 1)[:, None]\n",
                "        states = states.reshape((batch_size, 3, 13, 13))\n",
                "\n",
                "        for i, item in enumerate(data):\n",
                "            target_policies[i] = item[3]\n",
                "            target_values[i] = item[4]\n",
                "            \n",
                "        states = torch.tensor(states, dtype=torch.float32, device=device)\n",
                "        target_policies = torch.tensor(target_policies, dtype=torch.float32, device=device)\n",
                "        target_values = torch.tensor(target_values, dtype=torch.float32, device=device)\n",
                "        \n",
                "        optimizer.zero_grad()\n",
                "        out_policy, out_value = model(states)\n",
                "        \n",
                "        log_probs = F.log_softmax(out_policy, dim=1)\n",
                "        policy_loss = -(target_policies * log_probs).sum(dim=1).mean()\n",
                "        value_loss = F.mse_loss(out_value, target_values)\n",
                "        \n",
                "        loss = policy_loss + value_loss\n",
                "        loss.backward()\n",
                "        optimizer.step()\n",
                "        total_loss += loss.item()\n",
                "        \n",
                "    return total_loss / epochs"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Force CUDA\n",
                "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
                "print(f'Using device: {device}')\n",
                "if device.type == 'cuda':\n",
                "    print(f'GPU Name: {torch.cuda.get_device_name(0)}')\n",
                "\n",
                "model = SnakyNet(num_resBlocks=16, num_channels=256, board_size=13).to(device)\n",
                "buffer = ReplayBuffer(capacity=100000)\n",
                "\n",
                "import re\n",
                "drive_models = glob.glob(\"/content/drive/MyDrive/SnakyNet_Checkpoints/snaky_large_model_it*.pt\")\n",
                "root_models = glob.glob(\"/content/drive/MyDrive/snaky_large_model_it*.pt\")\n",
                "all_models = drive_models + root_models\n",
                "\n",
                "start_iteration = 13\n",
                "if all_models:\n",
                "    def get_it(path):\n",
                "        m = re.search(r'it(\\d+)\\.pt', path)\n",
                "        return int(m.group(1)) if m else -1\n",
                "    latest_model_path = max(all_models, key=get_it)\n",
                "    start_iteration = get_it(latest_model_path) + 1\n",
                "    print(f\"\\nFound checkpoint: {latest_model_path}\")\n",
                "    loaded = torch.load(latest_model_path, weights_only=False, map_location=device)\n",
                "    if isinstance(loaded, dict):\n",
                "        model.load_state_dict(loaded)\n",
                "        print(\"Successfully loaded weights from state_dict!\")\n",
                "    else:\n",
                "        model.load_state_dict(loaded.state_dict())\n",
                "        print(\"Successfully extracted and loaded weights from full model!\")\n",
                "else:\n",
                "    print(\"\\nNo checkpoints found. Starting from scratch!\")\n",
                "\n",
                "iterations = 1000\n",
                "games_per_iter = 100  # A100 is blazing fast\n",
                "batch_size = 512      # A100 has huge VRAM\n",
                "\n",
                "for it in range(start_iteration, iterations):\n",
                "    print(f'\\n--- Iteration {it}/{iterations} ---')\n",
                "    model.eval()\n",
                "    print('Starting Self-Play...')\n",
                "    data = self_play(model, num_games=games_per_iter, mcts_searches=100, device=device)\n",
                "    buffer.add(data)\n",
                "    \n",
                "    if len(buffer.buffer) >= batch_size: \n",
                "        loss = train(model, buffer, batch_size=batch_size, epochs=10, device=device)\n",
                "        print(f'Training Loss: {loss:.4f}')\n",
                "        \n",
                "    # Always save properly as state_dict so it loads anywhere!\n",
                "    save_path = f'/content/drive/MyDrive/SnakyNet_Checkpoints/snaky_large_model_it{it}.pt'\n",
                "    torch.save(model.state_dict(), save_path)\n",
                "    print(f'Saved Checkpoint to Google Drive! ({save_path})')\n"
            ]
        }
    ],
    "metadata": {
        "accelerator": "GPU",
        "colab": {
            "gpuType": "A100",
            "provenance": []
        },
        "kernelspec": {
            "display_name": "Python 3",
            "name": "python3"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 0
}

with open("colab_training_v5.ipynb", "w") as f:
    json.dump(notebook, f, indent=2)
print("colab_training_v5.ipynb generated!")
