"""Transpiles discovered Snakey StrategyTrees into Lean 4 formal code."""
from __future__ import annotations

from pathlib import Path
from typing import Any


def tree_to_lean4(node: Any, indent: int = 2) -> str:
  """Converts a strategy tree data structure into a Lean 4 StrategyTree expression."""
  sp = " " * indent
  if isinstance(node, tuple):
    if node[0] == "win":
      return ".win"
    elif node[0] == "move":
      # format: ('move', (m_x, m_y), [(b_coord, sub_tree), ...], default_sub_tree)
      m = node[1]
      branches = node[2] if len(node) > 2 else []
      default_tree = node[3] if len(node) > 3 else ("win",)

      if not branches:
        return f".move ({m[0]}, {m[1]}) fun _ =>\n{sp}  {tree_to_lean4(default_tree, indent + 2)}"

      lean_str = f".move ({m[0]}, {m[1]}) fun b =>\n"
      for i, (b_coord, sub_tree) in enumerate(branches):
        sub_lean = tree_to_lean4(sub_tree, indent + 4)
        if i == 0:
          lean_str += f"{sp}  if b = ({b_coord[0]}, {b_coord[1]}) then\n{sp}    {sub_lean}\n"
        else:
          lean_str += f"{sp}  else if b = ({b_coord[0]}, {b_coord[1]}) then\n{sp}    {sub_lean}\n"
      
      def_lean = tree_to_lean4(default_tree, indent + 4)
      lean_str += f"{sp}  else\n{sp}    {def_lean}"
      return lean_str

  return ".win"


def generate_lean_proof_file(
    strategy_tree: Any,
    lean_file_path: Path | str | None = None,
    tree_name: str = "snaky_winning_tree",
) -> str:
  """Generates a complete Lean 4 proof file containing the StrategyTree definition."""
  tree_code = tree_to_lean4(strategy_tree, indent=2)

  lean_code = f"""-- Auto-generated by FunSearch
import Snakey.SnakeyStrategy

open SnakeyStrategy

namespace SnakeyProof

/-- Machine-transpiled StrategyTree from FunSearch --/
def {tree_name} : StrategyTree :=
  {tree_code}

/-- Theorem: Machine-verified winning strategy for the Snaky Hexomino! -/
theorem maker_wins_snakey_verified :
  winning_strategy Snakey_base {tree_name} [] [] := by
  dsimp [{tree_name}, winning_strategy, Snakey_base]
  decide

end SnakeyProof
"""
  if lean_file_path:
    path = Path(lean_file_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(lean_code, encoding="utf-8")

  return lean_code
